(*                                                              -*-tuareg-*- *)
open Printf

let map = [ $(tests) ]

let print_help () =
  printf "usage: tests [option1] [option2] ...\n";
  printf "where an option is a test name or one of the following:\n";
  printf "--ps\t\tactivate ps (cairo) output (default: false)\n";
  printf "--pdf\t\tactivate pdf (cairo) output (false)\n";
  printf "--png\t\tactivate png (cairo) output (false)\n";
  printf "--tex\t\tactivate tex (tikz) output (false)\n";
  printf "--graphics\t\tactivate graphics output (true)\n";
  printf "Available tests are:\n";
  List.iter (fun (name, _) -> printf "%s  " name) map;
  printf "\n\nExample: ";
  printf "tests demo_zoom vector_field --nographics --pdf --png\n"

let backends title =
  let ret = Array.fold_left (fun acc -> function
    | "--ps" -> (sprintf "cairo PS %s.ps" title) :: acc
    | "--pdf" -> (sprintf "cairo PDF %s.pdf" title) :: acc
    | "--png" -> (sprintf "cairo PNG %s.png" title) :: acc
    | "--tex" -> (sprintf "tikz %s.tex" title) :: acc
    | "--graphics" -> "graphics hold" :: acc
    | _ -> acc) [] Sys.argv
  in
  if ret = [] then ["graphics hold"] else ret

let rec exec_test = function
  | "all" -> List.iter exec_test (List.map fst map)
  | name -> try
      let test = List.assoc name map in
      printf "%s\n" name;
      List.iter test (backends name)
    with Not_found -> Printf.printf "Test not found: %s" name

let () =
  if Array.length Sys.argv = 1 then print_help ()
  else Array.iteri (fun i x ->
                      if i <> 0 && String.sub x 0 2 <> "--"
                      then exec_test x) Sys.argv
